# Generated by Django 4.2.1 on 2023-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_topic_post_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
