# Generated by Django 4.2.1 on 2023-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, help_text='The date & time this article was published', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='The date & time this article was published', unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
